version: '3.3'

services:
    loki:
        image: grafana/loki:2.9.0
        expose:
            - 3100
        command: -config.file=/etc/loki/local-config.yaml
    promtail:
        image: grafana/promtail:2.9.0
        volumes:
            - logs:/var/log:rw
            - ./infrastructure/promtail.yml:/etc/promtail/config.yml
        command: -config.file=/etc/promtail/config.yml
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        expose:
            - 9090
    grafana:
        image: grafana/grafana:latest
        volumes:
            - grafanadata:/var/lib/grafana
        environment:
            - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        ports:
            - 3000:3000

    mongodb:
        image: mongo:5
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodata:/data/db
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 2s
            retries: 5
            start_period: 5s
        networks:
          - mynetwork

    go-service-with-metrics:
      build: .
      container_name: golgo-service-with-metrics
      environment:
        - APP_MONGO_URI=//replace
      ports:
        - "8081:8081"
      depends_on:
        - mongodb
      networks:
        - mynetwork

networks:
  mynetwork:

volumes:
  mongodata:    
  grafanadata:
  logs: