version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  golang_app:
    build: .
<<<<<<< Updated upstream
    container_name: golang_app
=======
    container_name: go-service-with-metrics
>>>>>>> Stashed changes
    environment:
      - APP_MONGO_URI=mongodb+srv://chetanrnimbalkar:4YyDyj2n8LinO19J@ch374ns.6butzms.mongodb.net
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongodb_data:
