version: '3.3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - go-service-with-metrics
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  go-service-with-metrics:
    build: .
    container_name: golgo-service-with-metrics
    environment:
      - APP_MONGO_URI=mongodb://mongodb:27017/vehicles_db
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongodb_data:
