apiVersion: v1
kind: Secret
metadata:
  name: vehiclesapp-secret
stringData:
  APP_MONGO_URI: bW9uZ29kYitzcnY6Ly9jaGV0YW5ybmltYmFsa2FyOjRZeUR5ajJuOExpbk8xOUpAY2gzNzRucy42YnV0em1zLm1vbmdvZGIubmV0
type: Opaque