name: Go Code Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  go-checks:
    name: Go Code Checks
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run format check
      id: format
      run: |
        make format || echo "Format check failed" > format_output.txt

    - name: Capture format output
      id: capture_format_output
      run: |
        echo "${{ steps.format.outputs.format_output }}" > format_output.txt

    - name: Run tests
      id: tests
      run: |
        make test || echo "Tests failed" > tests_output.txt

    - name: Capture tests output
      id: capture_tests_output
      run: |
        echo "${{ steps.tests.outputs.test_output }}" > tests_output.txt

    - name: Run coverage
      id: coverage
      run: |
        make coverage || echo "Coverage failed" > coverage_output.txt

    - name: Capture coverage output
      id: capture_coverage_output
      run: |
        echo "${{ steps.coverage.outputs.coverage_output }}" > coverage_output.txt

    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');

          const formatOutput = fs.readFileSync('format_output.txt', 'utf8').trim() || 'No output';
          const testOutput = fs.readFileSync('tests_output.txt', 'utf8').trim() || 'No output';
          const coverageOutput = fs.readFileSync('coverage_output.txt', 'utf8').trim() || 'No output';

          const comment = `
          ### Format Check Output
          ${formatOutput}

          ### Tests Output
          ${testOutput}

          ### Coverage Output
          ${coverageOutput}
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
