name: Go Code Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:

  go-checks:
    name: Go Code Checks
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests and capture output  # Indentation fixed here
      id: test_output
      run: |
        go test -coverprofile=coverage.out./... > test_output.txt
        echo "::set-output name=output::$(cat test_output.txt)"
    
    - name: Add PR comment with test output
      uses: actions/github-script@v6
      env:
        TEST_OUTPUT: ${{ steps.test_output.outputs.output }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const path = require('path');

          # Read the test output file and split it into lines
          const testOutputLines = fs.readFileSync(process.env.TEST_OUTPUT).split('\n');

          # Filter out empty lines and construct the comment body
          const commentBody = testOutputLines.filter(line => line.trim()!== '').join('\n\n');

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: commentBody
          });