name: Go Test and Format

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.18' # Specify the Go version you want to use

    - name: Run go fmt
      run: |
        go mod tidy
        go fmt./...

    - name: Run tests and generate coverage report
      run: |
        go test -coverprofile=coverage.out./...
        go tool cover -html=coverage.out > coverage.html

    - name: Add PR comment with coverage report
      uses: peter-evans/create-pull-request-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "Coverage report: \n$(cat coverage.html)"
