name: Go Code Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:

  go-checks:
    name: Go Code Checks
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests and capture output  # Indentation fixed here
      id: test_output
      run: |
        go test -coverprofile=coverage.out ./...
        echo "::set-output name=output::$(go tool cover -func=coverage.out)"
    
    - name: Add PR comment with test output
      uses: actions/github-script@v6
      env:
        TEST_OUTPUT: ${{join(steps.test_output.outputs.*, '\n')}}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const path = require('path');

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.TEST_OUTPUT
          });