name: Go Code Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  go-checks:
    name: Go Code Checks
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run format check
      run: |
        make format > format_output.txt || true

    - name: Run tests
      run: |
        make test > test_output.txt || true

    - name: Run coverage
      run: |
        make coverage > coverage_output.txt || true

    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');

          const formatOutput = fs.readFileSync('format_output.txt', 'utf8').trim() || 'No output';
          const testOutput = fs.readFileSync('test_output.txt', 'utf8').trim() || 'No output';
          const coverageOutput = fs.readFileSync('coverage_output.txt', 'utf8').trim() || 'No output';

          const comment = `
          ### Format Check
          ${formatOutput}

          ### Tests
          ${testOutput}

          ### Coverage
          ${coverageOutput}
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
