name: Go Test and Format

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.18' # Specify the Go version you want to use

    - name: Run go fmt
      run: |
        go mod tidy
        go fmt ./...

    - name: Run tests and generate coverage report
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out > coverage.html

    - name: Add PR comment with coverage report
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Read the coverage report
          const coverageReportPath = './coverage.html';
          const coverageReport = fs.readFileSync(path.resolve(coverageReportPath), 'utf8');

          // Create the comment content
          const commentContent = `Coverage report:\n\n${coverageReport}`;

          // Add the comment to the PR
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: commentContent
          });
